version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-apache
    container_name: sasno_web
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: sasno_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sasno
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
